Resources:
    DynamoDBUsersTable:
      Type: 'AWS::DynamoDB::Table'
      Description: testtable101
      Properties:
        TableName: test-success
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 10
          WriteCapacityUnits: 10
